### ISSUE TITLE
Suggestion: use number keys to set number of sides for drawing polygons

### ISSUE THREAD

**Issue by raphaelkabo** [akkartik/lines.love#1]
It's so nice to see love for Love! This is a wonderful idea for an app/markup standard.

I was thinking about how `o` and `0` are almost the same, and that in a way, you can conceive of a circle as having 0 'sides'. What if there was a set of shortcuts something like this:

- `0`: Draw a circle
- `1`: Draw a point (a _single_ point)
- `2`: Draw a line (a 'two-sided' shape)
- `3` - `9`: Draw a three-sided to nine-sided polygon.

This might expand the drawing UI nicely and it would still be easy to convey this data in simple markup.

**Comment by akkartik** [comment]
This is a tantalizing idea! One thing I struggled with was conflicting shortcuts. I wanted `c` to mean "circle", but it's already taken by "copy" (in the `ctrl+` incarnation). And "polygon" conflicts with "point". Right now I rationalize that "l" looks like a straight line in addition to being mnemonic, while "o" looks like a circle even if it's not mnemonic.

I've also wanted to have a clear separation between shortcuts for drawing vs writing just to minimize error messages I need to pop up and so on. I originally wanted to save `ctrl+` exclusively for drawing, but that didn't work given the number of idiomatic text shortcuts that just it (undo/redo, cut/paste/copy, find). Corralling all the drawing shortcuts to digits would be most excellent.

Drawbacks I can see:
* We lose the mnemonic aspect as I mentioned
* What should happen if you choose a 5 point polygon but release after 4 points? Or if you add 6 points?
* Sometimes you know in advance that you want to draw a 7-sided polygon. But maybe sometimes it seems like onerous planning?
* On a related note, this scheme might be giving up too many shortcuts to polygons. Maybe we should just do 0 for circles, 2 for lines, 3 for polygons (and 1 for adding points in polygon mode)? In this approach I'm thinking we'd still use letters for freehand/Manhattan/rectangle/square modes. Or maybe I should use `-` for Manhattan lines.

Thoughts most appreciated.

**Comment by johnblommers** [comment]
It's the ability to draw things in a text editor that is hugely appealing. Therefore I would support this idea. At this state of its development (alpha) adding or changing keyboard shortcuts is fair game.

**Comment by raphaelkabo** [comment]
Glad you like this! I think this idea will completely change the way polygons are drawn - I imagined them springing out of a centre point like the circles. You press 3, then drag and release from a central point for a triangle. And pull the cursor around to rotate, I think? I feel like an old painting program from my childhood worked this way. And it's a bit like Photoshop's shape tool.

What this loses is the ability to draw joining lines up into polygons freehand. That might actually be more valuable a feature to keep!

**Comment by akkartik** [comment]
LOL. That is so different, I might just make a fork to try it out.

I should say something about forks here. I've never before created an open source project that actually had other people using it :) I've noticed, though, that projects have a way of growing more complex over time and harder for newcomers to contribute to. Making changes just becomes fraught if a lot of people are going to be affected. At the same time, the need to keep everyone in the same fork also makes the codebase much more complex (menus, preferences, etc.), and leads to conflict. This is all very speculative, of course. Right now there's only a handful of us using this thing. I'm just planning for the future.

So I'd like to try something new here: to encourage people to create forks any time we have ideas for new features. That way changes to a single fork won't affect everyone and people can go off and try out new ideas. And we can pull changes into other forks as the people there want them.

I'd like for forks to be as first class as possible. Unless a fork does something I radically disagree with, I'll continue to test it, make it easier for others to discover. I might start linking to forks from the website, not yet sure what the experience should look like. I'll definitely actively suggest it to people, etc. If you give me access to it I'll try to port bugfixes to it. Might not be sustainable if we get a lot of forks, but we'll deal with that problem when we have it.

**Comment by akkartik** [comment]
One minor distinction that occurs to me: this approach to polygons will tend to encourage regular polygons. I wonder how one would draw rectangles, for example.

The center of a shape becomes much more emphasized in the author's mind. I don't typically think about the center of a box when I just want a box to write inside.

On the other hand a box I can write inside is quite klunky to create even in the current approach. So I'm open to trying new things..

**Comment by akkartik** [comment]
Oh, this idea causes a conflict. `ctrl+0` currently resets zoom. That's a common idiom.

**Comment by akkartik** [comment]
Sorry for the delay. I was tracking down instabilities in this repo for a few days, but there's now a new repo for this idea:

https://github.com/akkartik/lines-polygon-experiment

Tell me what you think!

**Comment by akkartik** [comment]
Oh, I meant to add: don't try to share important data between these forks. Make a backup before any switch. The way polygons are saved is different and incompatible.

**Comment by johnblommers** [comment]
OK so I've been trying to draw squares, rectangles and polygons using the standard version of `lines.love`. I must be getting slow because for the life of my I cannot figure out how to draw any of them. I just get a bunch of points. 

For example I have the little square symbol in the upper right hand corner so I know I'm in square drawing mode. Now what? All I get is dots where I click. So what am I missing?

**Comment by akkartik** [comment]
Sorry yeah, it takes a little getting used to. Press and hold as you draw the first edge, then press `p` to add more points. The whole polygon gets created without ever releasing the mouse.

Does this help? You can also press down `h` while holding down the mouse button to see some help.

I can hop on a quick video call with you if you like.

**Comment by johnblommers** [comment]
**AHA** so pressing **P** is what I am missing. No need for a video. The help should read:

> Press <kbd>p</kbd> to add a vertex to a polygon, rectangle or square.

**Comment by akkartik** [comment]
I see the problem. I don't have context-sensitive help for rectangles or squares.

**Comment by akkartik** [comment]
I'm going to close this issue as done now, but feel free to reopen it or open new issues at https://github.com/akkartik/lines-polygon-experiment if you try it out.
