### ISSUE TITLE
Change the insertion point to a proper cursor not a red dot

### ISSUE THREAD

**Issue by johnblommers** [akkartik/lines.love#2]
Using a red dot to mark the insertion point isn't really "proper."

Consider using an I-beam or a block as most other text editors and word processors do. I think it would make `lines.love` feel more familiar and inviting to the user.

**Comment by akkartik** [comment]
Does a vertical bar like this seem like an improvement? An I-beam requires a little more artistic talent, and I've always found a block slightly confusing. It feels more unambiguous to position the cursor in the boundary between characters rather than _on_ a character.

![Screenshot from 2022-06-08 22-59-38](https://user-images.githubusercontent.com/3161/172775784-6395c1b8-b2d1-48b0-a767-2b63e84aaaed.png)

**Comment by johnblommers** [comment]
Yes that vertical bar is much better.
Will it blink like a real cursor? 
Yes that's scope creep ;-)
Blinking allows the eye to find the cursor quickly on a wall of text.

**Comment by akkartik** [comment]
Yeah, that's a good point. I've been trying to keep the cursor easy to acquire as well.

Ok, it's a thicker line now and I have it blinking as well. I realize now the value of blinking: you can make the cursor thicker without occluding any text.

Do a `git pull`. Does it seem like an improvement? I tried to run some experiments:

* I tried pressing arrow keys randomly with my eyes closed, and then timing myself with a stopwatch to see how quickly my eyes could acquire the cursor.
* I looked away and moved the cursor randomly around to get a sense for whether I could see the cursor move out of the corner of my eye.

Results are kinda ambivalent? I think this will be decided on the basis of whether it feels better over a day or two.

**Comment by johnblommers** [comment]
Oh yes! This blinking red cursor now makes the entire editor feel much more comfortable. The old red dot seemed so alien LOL!

**Comment by akkartik** [comment]
Glad you like it! It's not too much code (https://github.com/akkartik/lines.love/commit/fe170fc579cc0), so I'll keep it unless we find a new issue with it.
