### ISSUE TITLE
lines.love becomes unresponsive when copying discontiniuous text

### ISSUE THREAD

**Issue by johnblommers** [akkartik/lines.love#3]
I was trying to copy some text out of two paragraphs with a  diagram between them. It worked maybe two  times but on the last attempt `lines.love` became unresponsive. The system prompted me to either let it run some more or to kill it. I opted to kill it.

While `lines.love` was unresponsive it was consuming one core as you can see from the attached screenshot. The distortion you see is because I have rotated the desktop cube to get a better view:

![Screenshot from 2022-06-08 22-24-44](https://user-images.githubusercontent.com/8484427/172771300-794c55c9-9534-47b5-8626-73c6204b1d7f.png)

**Comment by akkartik** [comment]
Looks like there doesn't even have to be a drawing in between. Copying (large) selections seems to take longer and longer with each successive copy. Let me investigate. Thank you for the report!

**Comment by akkartik** [comment]
Can I ask: how large is the file you're editing at the time?

**Comment by akkartik** [comment]
@johnblommers Could you try a `git pull` and see if things feel better? I think they might be, but I can't believe my eyes. Perhaps copying is fast, but something else has gotten sluggish? If so I haven't found it yet. So far everything seems fine to me. But I'd appreciate others testing. I'm going to wait a while to push this change to the website.

Technical details: I disabled the JIT compiler! https://github.com/akkartik/lines.love/commit/712dc95985

Funny story: I installed a profiler (https://github.com/2dengine/profile.lua) and ran it -- and all the performance problems went away! Magic profiler! Turns out it was disabling the JIT compiler.

**Comment by johnblommers** [comment]
```bash
wc lines.txt
  301  1294 46761 lines.txt
```

**Comment by johnblommers** [comment]
I just did the `git pull` and the copy-paste issue appears to have vanished. At least I cannot make it happen again.

**Comment by akkartik** [comment]
Yeah, so far it seems fine. Now pushing to the website.

**Comment by akkartik** [comment]
I spent some time yesterday reducing the memory footprint of lines.love. So far it feels like memory is a more limiting resource for this app than CPU, so I nudged the balance towards recomputing things rather than storing intermediate results. The app should now feel a bit snappier, particularly when copying and pasting. In the process I also changed how it behaves in a few situations (involving copy/paste and undo) to be a little more natural.

It still needs the JIT turned off, though. So far I can't figure out precisely what about this app interacts poorly with the JIT.

**Comment by johnblommers** [comment]
So when I look at `lines.love` using `top` it sits there using around 11.2% cpu. So on my 8-cpu system it's spinning most of one CPU. Now `lines.love` is just sitting there blinking its cursor. That seems like a lot to me. An anomaly.

So could this be related to poor JIT performance? I don't know.

Systems check:

On my system `lua  -v`  reports  `Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio` and from Synaptic I see `libluajit-5.1-2` is installed. The LOVE game engine is version `11.4ppa2` and a package just called `luajit 2.1.0` is not installed.

Being new to Lua I wanted to be sure there's nothing stupid going on at my end ;-)

**Comment by akkartik** [comment]
That's a good question, let me check on what `top` looks like on my side with and without the JIT.

My understanding is that LÖVE comes packaged with its own Lua and LuaJIT, doesn't use what's on your system.

**Comment by akkartik** [comment]
Also, if you're on Linux I believe 11% CPU means 11% of _one_ CPU.

**Comment by johnblommers** [comment]
This depends on the tool being used. Both `top` and `stacer` report 100% of one CPU when I  test it with `stress --cpu 4` but when I look at the output of Conky 12.5% means a single CPU is pinned.

That said, **you are correct** in that 11% figure I cited is 11% of one CPU so that CPU is not being pinned. Too bad.  The JIT issue is not going to be low hanging fruit.

**Comment by akkartik** [comment]
I think it's good news? It means Lua is fast enough without needing a lot of complicated code to speed things up :) But let me know if I'm missing something..

Also, someone pointed out that even if we don't use LuaJIT's JIT compiler, LÖVE gets a lot of benefit from LuaJIT's interpreter which is significantly faster than the regular Lua 5.1 interpreter.

**Comment by johnblommers** [comment]
I think it's good news. There is no point in premature code optimization at this juncture.

So LÖVE includes an optimized Lua interpreter. Is that why you chose it over alternatives? Indeed I'm curious why you chose LÖVE in the first place, a 2D game engine. For the framework perhaps?

**Comment by akkartik** [comment]
I actually wasn't aware of the optimized interpreter! All I noticed was that I could put pixels on the screen, that Lua programs were pretty fast without having complicated optimizations, and -- most important of all -- that Lua and LÖVE are both easy to build from source.

At the risk of boring you, I'll give you my rant. I have an unconventional belief: that the ills of current mainstream software stem from it being too hard to make changes to it. It's not enough to be open source (though that is necessary). To hold creators of software fully accountable to their users over the long term, it should be easy for any interested person to review a few changes in an afternoon. Software is fundamentally an interactive medium; to read code you have to be able to [run it](http://akkartik.name/post/comprehension). Make small changes and run with those changes.

In this spirit I spent a few years [building a computer from scratch](https://github.com/akkartik/mu). The idea was to make it easier for people to make changes without falling into deep holes that require huge skills to debug (as can often happen with undefined behavior in C).

However, I [eventually realized it was taking too long](https://lobste.rs/s/h4lnkn/what_are_you_doing_this_week#c_juxc6y). Lowering my standards and now being willing to consider some C in the stack, I cast about for alternatives and encountered Lua. But I was still turned off by how deep (and therefore hard to build) the graphics stack on Linux was. So I spent a while building [text mode apps in Lua](https://github.com/akkartik/teliva). Then I lowered my standards some more in the service of building apps people would actually care about -- and ended up at LÖVE. It uses a lot of C, and it doesn't really improve the buildability of the graphics stack, but it's at least very easy to build once you install the standard dependencies for a graphics stack (SDL, etc.)

**Comment by akkartik** [comment]
On my laptop lines.love uses up 6-7% of a 1.5GHz+ (AMD Ryzen 7 PRO 4750U) processor core when editing an empty file. When I open a 1.2MB text file with it and scroll down a few chapters (but still without any editing), `top` shows it using ~25-30% of a processor core.

**Comment by johnblommers** [comment]
It was shamefully easy to install `lines.love` in a Raspberry Pi 4B with 8 GB RAM running Raspberry Pi OS:

```bash
sudo apt install love
git clone https://github.com/akkartik/lines.love.git
love lines.love
```

In my testing `lines.love` uses about 12.9% of a CPU and there are four of them. That's pretty lightweight!
