### ISSUE TITLE
Crashing while editing diagrams

### ISSUE THREAD

**Issue by johnblommers** [akkartik/lines.love#4]
We were editing a diagram when BSOD occurs. We were deleting a few points then tried to add a line. On restart those changes were not kept.

Indeed even if we delete those few points and quit, those changes are not kept.

In fact even trying to draw a line from an existing lone point triggers the BSOD.

Crash report:

```bash
Error

text.lua:674: attempt to get length of field 'screen_line_starting_pos' (a nil value)


Traceback

[love "callbacks.lua"]:228: in function 'handler'
text.lua:674: in function 'in_line'
main.lua:280: in function <main.lua:274>
app.lua:34: in function <app.lua:25>
[C]: in function 'xpcall'
```

**Comment by akkartik** [comment]
Sorry about that :( Did you do a `git pull` recently?

**Comment by akkartik** [comment]
Could you do a `git pull` and try it now?

**Comment by akkartik** [comment]
I wrote a few more tests. Need to be more disciplined about it.

**Comment by johnblommers** [comment]
After doing a `git pull` the venerable `lines.love` is stable again. Problem solved.

By the way I find the best way to edit drawings is to maximize the window and zoom in as needed. This makes the drawing nice and big and makes fine precise editing possible.

**Comment by akkartik** [comment]
Thanks for your patience! I clearly still have a lot to learn about maintaining a project that's actually used by people.

**Comment by johnblommers** [comment]
The reason for my efforts at this end is that I enjoy testing interesting open source projects. I may have a bit more skill in ferreting out bugs that others. I report them gladly and feel that's my contribution. Finding bugs is pleasurable. Encountering and report bugs is a duty dammit LOL! But developers need not act alone in testing their products in the open source world. There is mutual benefit to testing by non-coders and users alike. 

That is all.

**Comment by akkartik** [comment]
I really appreciate it. I think one reason development slows in open source projects is a drop in the ratio of testers to users: http://akkartik.name/post/cil

**Comment by johnblommers** [comment]
That's a good read. Especially this part:

> But if the first time we hear of you is after we've made a new release, all mad-like because we totally broke you, we reserve the right to laugh you out of the room.

**Comment by akkartik** [comment]
I'd phrase it a little more kindly today. It's perfectly reasonable to not be concerned about implementation details when you start using a new project. Sometimes you have to encounter breakage to notice that you've grown to rely on something.

That sort of thing is why this post never left the draft stage. A license doesn't quite feel like the right mechanism here. I still noodle on this problem, though, of how to incentivize involvement in the open source projects we use.
