### ISSUE TITLE
Page Down crashes the app

### ISSUE THREAD

**Issue by johnblommers** [akkartik/lines.love#5]
I just did a `git pull` because I saw you made some changes to the code. But:

1. Launch `lines.love`
2. Press Page Down
3. Get BSOD (consistently)

```bash
Error

geom.lua:26: assertion failed!


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'assert'
geom.lua:26: in function 'on_shape'
drawing.lua:35: in function 'draw'
main.lua:252: in function 'draw'
app.lua:46: in function <app.lua:25>
[C]: in function 'xpcall'
```

**Comment by akkartik** [comment]
Huh! I can't reproduce it with either an empty file or my usual files. Could you email me the file you're editing?

Based on the `assert`, do you have any manhattan lines on the drawing at cursor after pressing pagedown?

**Comment by akkartik** [comment]
I think I've addressed the problem. Unfortunately, I think your data may be in a bad state :/ If you send it to me I'll fix it up for you. Basically I think what you may have done at some point is moved a point that was created as part of a horizontal or vertical line, so that the line is no longer horizontal/vertical. Does that seem like a possibility?

**Comment by johnblommers** [comment]
The data is test data and not important enough to bother with. I've renamed `lines.txt` and can no longer BSOD `lines.love` with Page Down. There were a number of figures in the test data all of them experimental to learn how to draw so I no longer need or want them anyway.

**Comment by johnblommers** [comment]
Possibly related. See attached `lines.txt` There is a Point P in DIAGRAM 2. Zoom in to see it more clearly. Hover over it so it highlights and press Ctrl+u to move it. BSOD:

```bash
Error

geom.lua:26: assertion failed!


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'assert'
geom.lua:26: in function 'on_shape'
drawing.lua:35: in function 'draw'
main.lua:263: in function 'draw'
app.lua:46: in function <app.lua:25>
[C]: in function 'xpcall'
```

[lines.txt](https://github.com/akkartik/lines.love/files/8932964/lines.txt)

**Comment by akkartik** [comment]
I can reproduce it! Thank you, I'll fix it.

**Comment by akkartik** [comment]
Thanks a lot for the report. My previous attempt was totally wrong. Please feel free to reopen this if you still see any issues.
